trigger: 
  - master

pool:
  name: agent

variables:
  dockerHubRepository: 'yuvrajpatil1/cachis'
  tag: '$(Build.BuildId)'

stages:
- stage: BuildAndPush
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: BuildPushJob
    displayName: 'Build and Push Redis Image'
    steps:
    - task: Docker@2
      displayName: 'Build redis image'
      inputs:
        repository: '$(dockerHubRepository)'
        command: 'build'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)'
        addPipelineData: false
        tags: |
          $(tag)
          latest

    - task: Docker@2
      displayName: 'Login to Docker Hub'
      inputs:
        command: 'login'
        containerRegistry: 'https://index.docker.io/v1/'
        username: '$(DOCKERHUB_USERNAME)'  # Set this in pipeline variables
        password: '$(DOCKERHUB_PASSWORD)'  # Set this in pipeline variables (mark as secret)

    - task: Docker@2
      displayName: 'Push redis image to DockerHub'
      inputs:
        repository: '$(dockerHubRepository)'
        command: 'push'
        addPipelineData: false
        tags: |
          $(tag)
          latest
